#!/bin/bash

# This test file will be executed as a duplicate test for the 'spec-kit' Feature.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f spec-kit --skip-autogenerated .

set -e

# Optional: Import test library bundled with the devcontainer CLI
source dev-container-features-test-lib

# Feature-specific tests
check "specify CLI installed (duplicate test)" which specify

# Report results
reportResults
