#!/bin/bash
set -e

# This test file will be executed as the main test for the 'spec-kit' Feature.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f spec-kit --skip-autogenerated .

# Optional: Import test library bundled with the devcontainer CLI
source dev-container-features-test-lib

# Feature-specific tests
check "specify version command" bash -lc "specify --version | grep -E '^specify [0-9]+.[0-9]+.[0-9]'"

# Report results
reportResults
