#!/bin/bash

# This test file will be executed as a duplicate test for the 'wokwi' Feature.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f wokwi --skip-autogenerated .

set -e

# Optional: Import test library bundled with the devcontainer CLI
source dev-container-features-test-lib

# Feature-specific tests
check "wokwi-cli installed (duplicate test)" which wokwi-cli

# Report results
reportResults